name: ANNI
version: '${project.version}'

main: net.nekozouneko.anni.ANNIPlugin
api-version: 1.21

authors: [Taitaitatata]
description: '${project.description}'
website: '${project.url}'

softdepend: [Votifier]
depend: [Vault, WorldEdit, WorldGuard]

libraries: ["org.xerial:sqlite-jdbc:3.48.0.0"]

commands:
  anni-admin:
    aliases: ["anniadmin"]
    description: "ANNI administration command"
    permission: anni.command.admin
    usage: "/<command> (arena|createMap|debug|map|set-lobby) <args>"
  anni:
    description: "ANNI command"
    permission: anni.command.anni
    usage: "/<command> (help|version)"
  combat-shop:
    aliases: ["cshop", "shop-combat"]
    description: "Combat Shop command"
    permission: "anni.command.combatshop"
    usage: "/<command>"
  potion-shop:
    aliases: ["pshop", "shop-potion"]
    description: "Potion Shop Command"
    permission: "anni.command.potionshop"
    usage: "/<command>"
  vote:
    description: "Vote command"
    permission: anni.command.vote
    usage: "/<command> <map>"
  kit:
    description: "Kit command"
    permission: anni.command.kit
    usage: "/<command>"
  suicide:
    aliases: [redeploy, kill]
    description: "Suicide command"
    permission: anni.command.suicide
    usage: "/<command>"
  charge:
    description: "Charge command"
    permission: anni.command.charge
    usage: "/<command>"
  player:
    description: "Player command"
    permission: anni.command.player
    usage: "/<command> [target]"

permissions:
  anni.mod.global_chat_on_spectator:
    default: op

  anni.command.player.other:
    default: op